pages:
  stage: deploy
  script:
     # message affiché dans la log lors de l'execution du traitement
     - echo 'Deploiement sur Gitlab pages'
     # on cree le repertoire public dans lequel gitlab pages va chercher ce qui doit être publié
     - mkdir -p public
     # on copie ce qui doit être publié dans public (ici le .html, potentiellement plusieurs)
     - mv docs/* public/
  artifacts:
    paths:
      - public
  only:
    # lancer automatiquement à chaque push sur la branche main
    - master